const Sequelize = require("sequelize");

const User = require("./user/user");
const Question = require("./test/question");
const Answer = require("./test/answer");
const Subject = require("./course/subject");
const Course = require("./course/course");
const Bookmark = require("./user/bookmark");
const TestSet = require("./test/test_set");
const TestQuestion = require("./test/test_question");
const LikeableEntity = require("./evaluation/likeable_entity");
const Like = require("./evaluation/like");
const Difficulty = require("./evaluation/difficulty");
const Freshness = require("./evaluation/freshness");
const CommentableEntity = require("./comment/commentable_entity");
const Comment = require("./comment/comment");
const PointLog = require("./user/point_log");
const PenaltyLog = require("./user/penalty_log");
const Attendance = require("./user/attendance");

const env = process.env.NODE_ENV || "development";
const config = require("../config/config")[env];
const db = {};

const sequelize = new Sequelize(config.database, config.username, config.password, config);
db.sequelize = sequelize;

db.User = User;
db.Question = Question;
db.Answer = Answer;
db.Subject = Subject;
db.Course = Course;
db.Bookmark = Bookmark;
db.TestSet = TestSet;
db.TestQuestion = TestQuestion;
db.LikeableEntity = LikeableEntity;
db.Like = Like;
db.Difficulty = Difficulty;
db.Freshness = Freshness;
db.CommentableEntity = CommentableEntity;
db.Comment = Comment;
db.PointLog = PointLog;
db.PenaltyLog = PenaltyLog;
db.Attendance = Attendance;

User.init(sequelize);
Question.init(sequelize);
Answer.init(sequelize);
Subject.init(sequelize);
Course.init(sequelize);
Bookmark.init(sequelize);
TestSet.init(sequelize);
TestQuestion.init(sequelize);
LikeableEntity.init(sequelize);
Like.init(sequelize);
Difficulty.init(sequelize);
Freshness.init(sequelize);
CommentableEntity.init(sequelize);
Comment.init(sequelize);
PointLog.init(sequelize);
PenaltyLog.init(sequelize);
Attendance.init(sequelize);

User.associate(db);
Question.associate(db);
Answer.associate(db);
Subject.associate(db);
Course.associate(db);
Bookmark.associate(db);
TestSet.associate(db);
TestQuestion.associate(db);
LikeableEntity.associate(db);
Like.associate(db);
Difficulty.associate(db);
Freshness.associate(db);
CommentableEntity.associate(db);
Comment.associate(db);
PointLog.associate(db);
PenaltyLog.associate(db);
Attendance.associate(db);

module.exports = db;
